### ISSUE TITLE
Regression affecting Python 3: PyString_FromStringAndSize

### ISSUE THREAD

**Issue by ghost** [lukeiwanski/tensorflow#234] opened 2018-04-21 06:06 UTC
Built as there https://developer.codeplay.com/computecppce/latest/getting-started-with-tensorflow
with an exception Python 3.5 was used.

OS: Linux bckpkol-ashatan 4.13.0-38-generic #43 16.04.1-Ubuntu SMP Wed Mar 14 17:48:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
From source. Git origin/dev/amd_gpu version. 01428d71e4a9ecdc763b54522e702393fa0c9240 commit.
Package: python3
Version: 3.5.1-3
Package: bazel
Version: 0.11.1
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9)
No CUDA, because I have RX 550 with working OpenCL
amdgpu-pro-17.40.2712-510357 driver, because latest wasn't working

The build was succesful. However it won't import.
Binaries: https://drive.google.com/open?id=1GJiN3JtVNBBeItLfnza-c7IYzBxH8LNL
Log: https://pastebin.com/6742kMMa

There was a similar bug already. https://github.com/tensorflow/tensorflow/issues/961
Now which file to fix?
ADD: https://drive.google.com/open?id=1BusauChEAdRsBnqKrjmqSWN79w4jNvHu 2.7 version just works by now.

**Comment by Meegooo** [comment] 2018-04-22 15:10
Exactly same issue. 
Ubuntu: 16.04.4 LTS
Bazel: 0.11.1
Python: 3.5.2
amdgpu-pro-17.50
gcc and g++: 5.4.0
Building from current HEAD at dev/amd_gpu (01428d71e4a9ecdc763b54522e702393fa0c9240)
In configurate everyhing no except jemalloc, OpenCL SYCL and ComputeCPP (no half types and double types).
Logs are exactly the same.
GPU: Rx 480

Seems to be working with 2.7

**Comment by lukeiwanski** [comment] 2018-04-22 18:22
Hello, 
Thanks for the bug report. 

Just to double check - is the issue still there without SYCL? I am guessing that this issue is not happening in the upstream?

By quick scan of the code every instance of the `PyString_FromStringAndSize` seems to be guarded by either `%#if PY_MAJOR_VERSION >= 3` or `#if PY_MAJOR_VERSION < 3`.

It seems that something is confusing `PY_MAJOR_VERSION`

I will try to reproduce this issue on the Monday and will keep you updated. 

Edit: perhaps `export CROSSTOOL_PYTHON_INCLUDE_PATH=/usr/include/python3.x` helps?

**Comment by Meegooo** [comment] 2018-04-23 05:44
If you meant running without SYCL, then the issue is still here.
Currently compiling on master without SYCL, gonna write when done.

`export CROSSTOOL_PYTHON_INCLUDE_PATH=/usr/include/python3.x` didn't help

PS. And yes, official tensorflow from pip repo works fine.

UPD: Master without SYCL works.

UPD2: To make sure that it's not a fluke (because yesterday I was getting random compile errors before it finally built on like fifth try) I recompiled again with [this config](https://gist.github.com/Meegooo/376ff24c2c002f27e947a7bddfca4a32). Still happens.

**Comment by lukeiwanski** [comment] 2018-04-23 10:52
Just to make sure for python 3.5 should be: `export CROSSTOOL_PYTHON_INCLUDE_PATH=/usr/include/python3.5`

I am working on reproducing this issue just now.

**Comment by lukeiwanski** [comment] 2018-04-23 20:09
@bckpkol / @Meegooo we have fix in PR https://github.com/lukeiwanski/tensorflow/pull/235
There are some comments that we need to address but in principal you should be able to apply this patch to work around it:

```diff --git a/third_party/sycl/crosstool/CROSSTOOL.tpl b/third_party/sycl/crosstool/CROSSTOOL.tpl
index eb16a4d..cbec2a3 100755
--- a/third_party/sycl/crosstool/CROSSTOOL.tpl
+++ b/third_party/sycl/crosstool/CROSSTOOL.tpl
@@ -55,11 +55,8 @@ toolchain {
   cxx_builtin_include_directory: "/usr/local/include"
   cxx_builtin_include_directory: "/usr/include"
   cxx_builtin_include_directory: "%{COMPUTECPP_ROOT_DIR}%"
-  cxx_builtin_include_directory: "%{PYTHON_INCLUDE_PATH}%"
 
   cxx_flag: "-std=c++11"
-  cxx_flag: "-isystem"
-  cxx_flag: "%{PYTHON_INCLUDE_PATH}%"
   cxx_flag: "-fsycl-ih-last"
   cxx_flag: "-sycl-driver"
   cxx_flag: "-Xclang"
```

**Comment by lukeiwanski** [comment] 2018-04-24 11:19
This should be fixed now in:  dae264a

**Comment by Meegooo** [comment] 2018-04-24 14:33
Seems to be working.

**Comment by lukeiwanski** [comment] 2018-04-24 15:42
@Meegooo  thanks for the feedback!
@bckpkol can we close this issue?

**Closed as completed** 2019-01-07 14:22 UTC
